### ISSUE TITLE
Split Samples differently based on their underlying type

### ISSUE THREAD

**Issue by FriederikeHanssen** [qbicsoftware/statistics-cli#8]
"Another point: at the sample level I would prefer to have the R-RNA,M-RNA and RNA under one tab called "RNA". Currently it looks like we are still working the most on proteins. That is certainly not true and should be reflected by numbers."

**Comment by naepfel** [comment]
I haven’t checked the portlet yet, but I can confirm that proteins shouldn’t be the largest source

**Comment by FriederikeHanssen** [comment]
This has been added.
